version: "3.8"

services:
    handle_service:
        build:
            context: "."
            dockerfile: ./docker/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - 9000:9000

    nginx:
        build:
            context: "."
            dockerfile: ./docker/nginx.Dockerfile
        volumes:
            - ./public:/var/www/html/public
        ports:
            - "80:80"
