version: "3.8"

services:
    handle_service:
        # tty: true
        # stdin_open: true
        build:
            context: "."
            dockerfile: ./docker/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - 8000:8000

    # nginx:
    #    build:
    #       context: '.'
    #       dockerfile: ./docker/nginx.Dockerfile
    #    ports:
    #       - '80:80'
    #    restart: always
